name: weatherfast
description: "WeatherFast"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  dynamic_color: ^1.8.1
  flutter_typeahead: ^5.2.0
  geolocator: ^14.0.2
  permission_handler: ^11.1.0
  intl: ^0.17.0
  package_info_plus: ^8.1.2
  timezone: ^0.10.1
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/backgrounds/
    - assets/profilepics/
    - assets/appicon/
